
/* ===========================
*          INCLUDES
* =========================== */
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <linux/fb.h>

#include "../include/fb_driver.h"

#include "../lvgl/lvgl.h"
/* ===========================
 *           DEFINES
 * =========================== */
#define FB_DEVICE "/dev/fb0"
#define DRAW_BUF_LINES 30 /* lines per draw buffer */

static int s_fb_fd = 1;
static uint8_t *s_fb_mem = NULL;
static size_t s_fb_size = 0;

static struct fb_var_screeninfo s_vinfo;
static struct fb_fix_screeninfo s_finfo;

static lv_display_t *s_disp = NULL;
static lv_color_t *s_buf1 = NULL;
static lv_color_t *s_buf2 = NULL;

/* ===========================
 *     LOCAL VARIABLES
 * =========================== */


/* ===========================
 *    LOCAL PROTOTYPES
 * =========================== */
static void fb_flush_cb(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map);

/* ===========================
 *   GLOBAL FUNCTIONS
 * =========================== */
int fb_driver_init(void) {
    
    /*Open the Linux framebuffer device*/
    s_fb_fd = open(FB_DEVICE, O_RDWR);
    if(s_fb_fd < 0) {
        perror("[fb] open");
        return -1;
    }

    /*read information from the screen  (resolution, color depth, etc.)*/
    if(ioctl(s_fb_fd, FBIOGET_VSCREENINFO, &s_vinfo) < 0) { //ioctl = I/O control operation
        perror("[fb] FBIOGET_VSCREENINFO");
        close(s_fb_fd);
        return -1;
    }
    if(ioctl(s_fb_fd, FBIOGET_FSCREENINFO, &s_finfo) < 0) {
        perror("[fb] FBIOGET_FSCREENINFO");
        close(s_fb_fd);
        return -1;
    }

    printf("[fb] %ux%u %ubpp\n", s_vinfo.xres, s_vinfo.yres, s_vinfo.bits_per_pixel);

    /*Calculate the framebuffer size and map it into user-space memory*/
    s_fb_size = (size_t)s_finfo.line_length * s_vinfo.yres;
    s_fb_mem = mmap(NULL, s_fb_size, PROT_READ | PROT_WRITE, MAP_SHARED, s_fb_fd, 0);

    if(s_fb_mem == MAP_FAILED) {
        perror("[fb] mmap");
        close(s_fb_fd);
        return -1;
    }

    /*Allocate the LVGL draw buffers used for partial rendering*/
    size_t buf_px = (size_t)s_vinfo.xres * DRAW_BUF_LINES;
    s_buf1 = malloc(buf_px * sizeof(lv_color_t));
    s_buf2 = malloc(buf_px * sizeof(lv_color_t));
    if(!s_buf1 || !s_buf2) {
        fprintf(stderr, "[fb] malloc draw buffer failed\n");
        munmap(s_fb_mem, s_fb_size);
        close(s_fb_fd);
        return -1;
    }

    /*register display on LVGL*/
    s_disp = lv_display_create(s_vinfo.xres, s_vinfo.yres);
    lv_display_set_flush_cb(s_disp, fb_flush_cb);

    // Use partial rendering to reduce memory usage by updating the screen in small regions (chunks). = LV_DISPLAY_RENDER_MODE_PARTIAL
    lv_display_set_buffers(s_disp, s_buf1, s_buf2, buf_px * sizeof(lv_color_t), LV_DISPLAY_RENDER_MODE_PARTIAL);

    return 0;
}

void fb_driver_deinit(void) {
    free(s_buf1);
    free(s_buf2);

    if(s_fb_mem && (s_fb_mem != MAP_FAILED)) {
        munmap(s_fb_mem, s_fb_size);
    }
    if(s_fb_fd >= 0) {
        close(s_fb_fd);
    }
}

/* ===========================
 *   LOCAL FUNCTIONS
 * =========================== */
/**
 * @brief Flushes a rendered LVGL area to the Linux framebuffer.
 *
 * This callback is invoked by LVGL whenever a portion of the display has
 * been rendered and needs to be written to the framebuffer. The function
 * copies the rendered pixels line by line from the LVGL draw buffer into
 * the corresponding framebuffer memory region.
 *
 * @param disp   Pointer to the LVGL display instance.
 * @param area   Rectangle defining the region of the screen to update.
 * @param px_map Pointer to the pixel buffer generated by LVGL for the region.
 *
 * @return None.
 */
static void fb_flush_cb(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map) {
    // Get the width (in pixels) of the area that needs to be updated.
    int32_t width_area = lv_area_get_width(area);

    // Copy the rendered image line by line into the framebuffer.
    for(int32_t y = area->y1; y <= area->y2; y++) {
        // Calculate the destination address of the current row in the framebuffer.
        uint8_t *dst = s_fb_mem + 
            (y * s_finfo.line_length) + 
            (area->x1 * (s_vinfo.bits_per_pixel / 8));

        // Number of bytes to copy for this row.
        size_t row_bytes = (size_t)width_area * (s_vinfo.bits_per_pixel / 8);
        // Copy one row of pixels from the LVGL draw buffer to the framebuffer.
        memcpy(dst, px_map, row_bytes);
        // Advance to the next row in the LVGL draw buffer.
        px_map += row_bytes;
    }
    // Notify LVGL that the flush operation has completed.
    lv_display_flush_ready(disp);
}